# Основной шаблон для cv сервисов
x-cv-base: &cv-base
  build: services/cv
  tty: true
  init: true
  depends_on:
    postgres:
      condition: service_healthy
    rabbitmq:
      condition: service_healthy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  env_file:
    - services/cv/.env  # базовый .env



services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-rmuser}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-rmpassword}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 15672:15672
      - 5672:5672

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 6
  
  postgres:
    image: postgres:14.21-trixie
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    ports:
      - "5432:5432"
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  cv_cameras_1_2:
    <<: *cv-base
    environment:
      - CAMERA_IDS=[1,2]

  cv_cameras_3_4:
    <<: *cv-base
    environment:
      - CAMERA_IDS=[3,4]

  cv_cameras_5_6:
    <<: *cv-base
    environment:
      - CAMERA_IDS=[5,6]

  analytics:
    build: services/analytics
    env_file:
      - services/analytics/.env
    tty: true
    init: true
    depends_on:
      postgres:
        condition: service_healthy 
      rabbitmq:
        condition: service_healthy

  notifications:
    build: services/notifications
    env_file:
      - services/notifications/.env
    ports:
      - "8002:8002"
    tty: true
    init: true
    depends_on:
      postgres:
        condition: service_healthy 
      rabbitmq:
        condition: service_healthy

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"
      - "8889:8889"
      - "8888:8888"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped


  configuration:
    build: services/configuration
    env_file:
      - services/configuration/.env
    ports:
      - "8000:8000"
    tty: true
    init: true
    depends_on:
      postgres:
        condition: service_healthy 
    

  frontend:
    build: services/frontend
    env_file:
      - services/frontend/.env
    ports:
      - "5173:5173"
    tty: true
    init: true
    
  # file streamer for demo
  ffmpeg-streamer:
    image: jrottenberg/ffmpeg:latest
    container_name: ffmpeg-streamer
    volumes:
      - ./videos:/videos
    restart: unless-stopped
    entrypoint: /bin/sh
    command: >
     -c "
     ffmpeg -re -stream_loop -1 -fflags +genpts -avoid_negative_ts make_zero -i /videos/camera1.mp4 \
     -c:v libx264 -preset veryfast -tune zerolatency \
     -x264-params 'bframes=0:ref=1:keyint=1:scenecut=0' \
     -r 20 -b:v 3000k -maxrate 2500k -bufsize 5000k -g 20 -keyint_min 20 \
     -an \
     -f rtsp rtsp://mediamtx:8554/camera_1 &

     # same command for every mock camera stream 

     wait
     "
    depends_on:
      - mediamtx
volumes:
  postgres_data: